# Generated by Django 4.0.6 on 2022-07-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_dummy_app", "0002_auto_20211206_0602"),
    ]

    operations = [
        migrations.AlterField(
            model_name="continent",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="country",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
